SUP-1320: Remove deprecated deletion_protection from pipeline
buildkite/terraform-provider-buildkite pull request #373
Opened 2023-08-23 06:25 UTC by lizrabuya

2023-08-23 14:05 UTC, jradtilbrook requested changes

2023-08-23 14:05 UTC, jradtilbrook commented on docs/resources/pipeline.md
> --   `deletion_protection` - **DEPRECATED** (Optional) Set to either `true` or `false`. When set to `true`, `destroy` actions on a pipeline will be blocked and fail with a message "Deletion protection
This needs line 56 removed as well

2023-08-24 05:36 UTC, jradtilbrook requested changes

2023-08-24 05:36 UTC, jradtilbrook commented on docs/resources/pipeline.md
> +configuration makes more sense and will apply to all pipelines managed through terraform. Please see `archive_pipeline_on_delete`.
I think this is a bad merge. This should have been removed as well

2023-08-24 05:38 UTC, mcncl requested changes

2023-08-24 05:38 UTC, mcncl commented on docs/resources/pipeline.md
Probably needs deleting?

2023-08-24 05:38 UTC, mcncl commented on docs/resources/pipeline.md
Resolving as same as above.

2023-08-24 06:10 UTC, mcncl approved these changes

2023-08-24 06:15 UTC, james2791 approved these changes

2023-08-24 11:21 UTC, jradtilbrook approved these changes

2023-08-24 11:21 UTC, merged