SUP-1539 Allow reading of webhook_url on create only
buildkite/terraform-provider-buildkite pull request #450
Opened 2023-12-07 05:35 UTC by lizrabuya

<type: fix | feat | build | chore | ci | docs | style | refactor | perf | test >(scope)[!]: [description]

## PR checklist:
- [ ] `docs/` updated
- [ ] tests added
- [ ] an example added to `examples/` (useful to demo new field/resource)
- [ ] `CHANGELOG.md` updated with pending release information

### Example
test(pipeline resource): Add a test to resource_pipeline_test to check for valid name chars

## PR checklist:
- [ ] `docs/` updated <-- No need for a doc update, no user impact
- [x] tests added <-- Tests were added
- [ ] an example added to `examples/` (useful to demo new field/resource) <-- No demo required as no user impact
- [x] `CHANGELOG.md` updated with pending release information <-- Changes were made

#### To ! or not to !
`!` denotes a breaking change, in this example the test does **not** cause a breaking change and so `!` is not required.

A `BREAKING CHANGE` footer may also be used:

```
feat: strip non-ASCII chars from pipeline name
BREAKING CHANGE: no longer replaces non-ASCII with "blank symbols"
```

2023-12-11 00:05 UTC, james2791 requested changes
Should we also change the received GraphQL pipeline [fragment](https://github.com/buildkite/terraform-provider-buildkite/blob/main/buildkite/graphql/pipeline.graphql#L34-L36) so the provider doesn't obtain the `webhookUrl` as an attribute from the API on creates? At the moment, pipeline reads/updates will "obtain" it, but not actually use it as its shared between the functions.

2023-12-18 00:26 UTC, lizrabuya commented
I have made the necessary change to not expose WebhookUrl on plan updates from the schema

2023-12-18 00:49 UTC, mcncl submitted a review, later dismissed

2023-12-18 03:30 UTC, james2791 approved these changes
🎸

2023-12-18 03:35 UTC, merged